chore: update error handling and wrap token response

diff --git a/bin/chinmina_token b/bin/chinmina_token
--- a/bin/chinmina_token
+++ b/bin/chinmina_token
@@ -34,17 +34,19 @@ chinmina_response=$(curl --silent --show-error --fail \
   --header "Content-Type: text/plain" \
   --header "Accept: text/plain")
 
-token_exists=$(echo "$chinmina_response" | jq 'has("token")')  
+token_exists="$(echo "$chinmina_response" | jq 'has("token")')"
 
-if $token_exists; then
-    chinmina_token=$(echo "$chinmina_response" | jq -r '.token')
-    if [ ${#chinmina_token} -eq 0 ]; then
-        echo "request failed: token doesn't exist" >&2
-        exit 1
-    fi
-else
-    echo "request failed: token not found" >&2
+if [[ "${token_exists}" == "false" ]]; then
+    echo "request failed: no token returned in Chinmina response" >&2
     exit 1
 fi 
 
-echo $chinmina_token 
+if [[ "${token_exists}" == "true" ]]; then
+    chinmina_token=$(echo "$chinmina_response" | jq -r '.token')
+    if [[ ${#chinmina_token} -eq 0 ]]; then
+        echo "request failed: token doesn't exist in Chinmina response" >&2
+        exit 1
+    fi
+fi
+
+echo "${chinmina_token}" 
