fix: flatten logic and remove unnecessary assignment

diff --git a/bin/chinmina_token b/bin/chinmina_token
--- a/bin/chinmina_token
+++ b/bin/chinmina_token
@@ -6,6 +6,7 @@ cache_file="/tmp/oidc_auth_token_${BUILDKITE_JOB_ID}.cache"
 url="$BUILDKITE_PLUGIN_CHINMINA_TOKEN_LIBRARY_CHINMINA_URL"
 audience="$BUILDKITE_PLUGIN_CHINMINA_TOKEN_LIBRARY_AUDIENCE"
 args="" # No data is required to fetch the token
+
 # Caches the OIDC token for 5 minutes.
 if [[ -f "${cache_file}" && -s "${cache_file}" && $(find "${cache_file}" -mmin -5) ]]; then
   oidc_auth_token="$(< "${cache_file}")"
@@ -24,8 +25,6 @@ else
   path="organization/token/${profile_name}"
 fi
 
-oidc_auth_token=$(cat "$cache_file")
-
 # POST request to fetch token from Github App
 chinmina_response=$(curl --silent --show-error --fail \
   --request POST "${url}/${path}" \
@@ -37,16 +36,14 @@ chinmina_response=$(curl --silent --show-error --fail \
 token_exists="$(echo "$chinmina_response" | jq 'has("token")')"
 
 if [[ "${token_exists}" == "false" ]]; then
-    echo "request failed: no token returned in Chinmina response" >&2
-    exit 1
+  echo "request failed: no token returned in Chinmina response" >&2
+  exit 1
 fi 
 
-if [[ "${token_exists}" == "true" ]]; then
-    chinmina_token=$(echo "$chinmina_response" | jq -r '.token')
-    if [[ ${#chinmina_token} -eq 0 ]]; then
-        echo "request failed: token doesn't exist in Chinmina response" >&2
-        exit 1
-    fi
+chinmina_token="$(echo "$chinmina_response" | jq -r '.token')"
+if [[ ${#chinmina_token} -eq 0 ]]; then
+  echo "request failed: empty token returned by Chinmina" >&2
+  exit 1
 fi
 
 echo "${chinmina_token}" 
