chore: add error handling for invalid json responses

diff --git a/bin/chinmina_token b/bin/chinmina_token
--- a/bin/chinmina_token
+++ b/bin/chinmina_token
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+echo "This starts"
 # This script is responsible for getting a token for a given profile (or the default)
 profile_name=$1
 oidc_cached_path="/tmp/oidc_auth_token_${BUILDKITE_JOB_ID}.cache"
@@ -9,7 +10,7 @@ args="" # No data is required to fetch the token
 if [[ ${profile_name} == "default" || ${profile_name} == "repo:default" ]]; then
   path="token"
 else
-  path="organization/token/${profile_name}"
+  path="organization/token/${profile_name}"s
 fi
 
 oidc_auth_token=$(cat "$oidc_cached_path")
@@ -26,5 +27,10 @@ chinmina_response=$(curl --silent --show-error --fail \
 
 # Uses jq to filter the json object and retrieve the token value
 chinmina_token=$(echo "$chinmina_response" | jq '.token')
+
+if [ $? -ne 0 ]; then
+    echo "JSON parsing failed"
+    return 1
+fi
 
 echo "$chinmina_token"  
