feat: retrieve and export tokens for environment array

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -36,5 +36,9 @@ while IFS='=' read -r var_name profile; do
     echo "Empty profile for: '$var_name'" >&2
     exit 1
   fi
-  export "${var_name}=${profile}"  # interim: profile as value
+  if ! token=$(chinmina_token "$profile"); then
+    echo "Token retrieval failed for: '$profile'" >&2
+    exit 1
+  fi
+  export "${var_name}=${token}"
 done < <(plugin_read_list BUILDKITE_PLUGIN_CHINMINA_TOKEN_ENVIRONMENT)
